name: PR Linting

on:
  pull_request:
    branches:
      - develop
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Fetch all branches
        run: git fetch --all

      - name: Run commitlint
        run: |
          npx commitlint --from=origin/develop --to=HEAD

  prlint-reloaded:
    runs-on: ubuntu-latest

    steps:
      - uses: maor-rozenfeld/prlint-reloaded@v1
        with:
          title-regex: ^AK-\d+:.[A-Z][a-z]+
          error-message: Your title must be in the format.

      - uses: maor-rozenfeld/prlint-reloaded@v1
        with:
          title-regex: ^\S+\s+\S+\s+\S+
          error-message: Your title must have at least three words

      - uses: maor-rozenfeld/prlint-reloaded@v1
        with:
          title-regex: ^(?!\S+ing\s)(?!\S+ed\s)
          error-message: Use imperative mood (i.e write "Fix", not "Fixed" or "Fixing")
